experiment_name: 'experiment_01'
datasets:
    path: '/usr/src/processed-data/x.csv'
    path_y: '/usr/src/processed-data/y.csv'
    x: 
        - 'total_cases'
        - 'new_cases'
        - 'total_deaths'
        - 'reproduction_rate'
        - 'total_tests'
        - 'new_tests'
        - 'positive_rate'
        - 'tests_per_case'
        - 'tests_units'
        - 'total_vaccinations'
        - 'people_vaccinated'
        - 'people_fully_vaccinated'
        - 'total_boosters'
        - 'new_vaccinations'
        - 'stringency_index'
        - 'population'
        - 'population_density'
        - 'median_age'
        - 'aged_65_older'
        - 'aged_70_older'
        - 'gdp_per_capita'
        - 'extreme_poverty'
        - 'cardiovasc_death_rate'
        - 'diabetes_prevalence'
        - 'female_smokers'
        - 'male_smokers'
        - 'handwashing_facilities'
        - 'hospital_beds_per_thousand'
        - 'life_expectancy'
        - 'human_development_index'
        - 'year'
        - 'month'
        - 'day'
        
    y:
        - 'new_deaths'
    train_test_split:
        test_size: 0.3
        random_state: 696
models:
    sklearn:
        ensemble:
            - 'RandomForestRegressor'
            - 'GradientBoostingRegressor'
        linear:
            - 'LinearRegression'
            - 'SGDRegressor'
            - 'BayesianRidge'
            - 'ElasticNet'
is_scaled: 
    y: 0
    x: 0
    scaler: 'StandardScaler'
